import "~/styles/globals.css";

import { Inter, Gothic_A1 } from "next/font/google";
import { type Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { CartProvider } from "../../Cart/contexts/cartContext";
import { Toaster } from "../../components/ui/sonner";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const fontAccent = Gothic_A1({
  subsets: ["latin"],
  variable: "--font-gothic-a1",
  weight: ["900"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const messages = await getMessages();

  return (
    <html lang="en" className={`${fontSans.variable} ${fontAccent.variable}`}>
      <body className="bg-secondary">
        <CartProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </CartProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
